scripts/restore-etc: make diff fail if flash cannot be read
Issuing "config diff" when the flash is already mounted results in a
full diff being displayed instead of the mount error message. Let's
make sure we can abort in such a case. If the user wants to check
what has changed from the rom, they can issue "config diff factory"
instead.

diff --git a/scripts/restore-etc b/scripts/restore-etc
--- a/scripts/restore-etc
+++ b/scripts/restore-etc
@@ -316,6 +316,11 @@ if [ $DIFF -eq 1 ]; then
     exit 1
   fi
   restore_config
+  if [ $? -ne 0 ]; then
+    echo "Cannot load the current config from the flash." >&2
+    [ -n "$ROOTDIR" -a "$ROOTDIR" != "/" ] && rm -rf "$ROOTDIR"
+    exit 1
+  fi
 
   flx check --ignore-dot --ignore-link --ignore-date "$ROOTDIR"/etc=etc /etc=etc \
     | awk '/^. [^d]/ { print $9 }' | sort -u \
