scripts: update restore-etc and save-etc to support a reference image
In order to support having /etc in RAM without having to back up
everything, we now move the original /etc into /usr/share/factory/base-etc
during the packaging, and restore-etc is responsible for picking files
from it at boot time and complete them with what it finds in the backed
up configuration.

Another new file "/usr/share/factory/ignore-files" is used to indicate
which files are never saved by save-etc even if changed, and are never
restored even if present in the backed up configuration.

Both save-etc and restore-etc now mount the flash by themselves, so that
they does not need mount-flash to have previously been run.

diff --git a/scripts/restore-etc b/scripts/restore-etc
--- a/scripts/restore-etc
+++ b/scripts/restore-etc
@@ -1,22 +1,83 @@
 #!/bin/bash
 
 # This script unmounts /etc, mounts a ramfs onto it, and extracts
-# /flash/cfg/config.{cur,bak,fac} into it.
+# /flash/cfg/config.{cur,bak,fac} into it. If an argument is passed, it will be
+# used as a local config file and the restoration will proceed from this file.
+# Note: this script checks the existence of /etc/config.rc in order to detect
+# if a previous config had already been loaded.
+
+# get out of /flash and /etc just in case.
+cd /
 
 export PATH=/bin:/sbin:/usr/bin:/usr/sbin
-FLASH=/flash/cfg
+FLASHDIR=/flash
+FLASHCFG=${FLASHDIR}/cfg
 FILE=/etc/.restored
+EXCLUDE=/usr/share/factory/ignore-files
+REFERENCE=/usr/share/factory/base-etc
 FORCE=0
 VERBOSE=0
+CFGFILE=
+
+# Mounts the flash in $FLASHDIR.
+# This checks /proc/cmdline for the LAST 'flash=' statement, and
+# uses its value as a /dev entry to mount it read-only into $FLASHDIR.
+# Returns 0 if OK, 1 otherwise.
+# DOES NOT unmounts $FLASHDIR first if previously mounted, but returns with
+# an error indicating a resource access conflict.
+mount_flash_ro() {
+  local flash
+  flash="$(cat /proc/cmdline)"
+  if [ -n "${flash##*flash=*}" ]; then
+    echo "No flash device specified in /proc/cmdline."
+    return 1
+  fi
+  flash=${flash##*flash=}
+  flash=${flash%% *}
+  [ -n "${flash##/dev/*}" ] && flash="/dev/$flash"
+
+  echo "Mounting ${flash} on $FLASHDIR..."
+  if ! mount -n -r $flash $FLASHDIR >/dev/null 2>&1; then
+    echo "Error: mount failed."
+    return 1
+  fi
+  return 0
+}
+
+# unmounts /flash
+umount_flash() {
+  if ! umount -d $FLASHDIR >/dev/null 2>&1; then
+    cd /
+    if ! umount -d $FLASHDIR >/dev/null 2>&1; then
+      echo "Error: cannot unmount $FLASHDIR"
+      return 1
+    else
+      echo "Warning: ${0##*/} forgot to leave $FLASHDIR before unmounting it."
+    fi
+  fi
+  return 0
+}
 
 while [ $# -gt 0 ]; do
   if [ ".$1" = ".-f" ]; then FORCE=1
   elif [ ".$1" = ".-v" ]; then VERBOSE=1
-  else
+  elif [ -z "${1##-*}" ]; then
     echo "Unknown argument: $1"
+    echo "Valid options are :"
+    echo "  -f : force update and ignore local changes ;"
+    echo "  -v : only check whether files have been modified ;"
+    echo "  <file> : restore from this file instead of flash."
+    exit 1
+  else
+    break
   fi
   shift
 done
+
+if [ $# -gt 0 ]; then
+  CFGFILE="$1"
+  shift
+fi
 
 if [ $VERBOSE -eq 1 ]; then
   echo "List of files modified since last backup."
@@ -30,20 +91,59 @@ if [ $FORCE -eq 0 -a -e $FILE ] && \
   exit 1;
 fi 
 
-for config in $FLASH/config.cur $FLASH/config.bak $FLASH/config.fac; do
-  if [ -s $config ] && [ $(tar ztf $config 2>/dev/null|wc -l) -gt 0 ]; then
-    if [ -e /etc/passwd ]; then
-      umount /etc >/dev/null 2>&1
+# restore from local file ?
+if [ -n "$CFGFILE" ]; then
+  if [ -s "$CFGFILE" ] && [ $(tar ztf "$CFGFILE" 2>/dev/null|wc -l) -gt 0 ]; then
+    if [ -e /etc/config.rc ]; then
+      while umount /etc >/dev/null 2>&1; do : ; done
     fi
-    mount -t ramfs /etc /etc
-    tar -C /etc --strip-components=1 -zxf $config >/dev/null 2>&1
-    if [ $? -eq 0 -a -s /etc/passwd ]; then
-      rm -f $FILE ; touch $FILE ; chmod 600 $FILE
-      flx sign --ignore-dot /etc | grep -vwF "${FILE#/}" >$FILE
-      echo ${config##*/}
+
+    mount -n -t ramfs /etc /etc
+    (tar -C $REFERENCE --one-file-system -cf - . | tar -C /etc -xf -) >/dev/null 2>&1
+    tar -C /etc --exclude-from $EXCLUDE --strip-components=1 -zxf "$CFGFILE" >/dev/null 2>&1
+    # ignore the return code, because some files may come with extra CR/LF.
+    if [ -s /etc/config.rc ]; then
+      ( rm -f /etc/blkid.tab{,.old}; \
+        rm -f $FILE ; touch $FILE ; chmod 600 $FILE; \
+        flx sign --ignore-dot /etc | grep -vwF "${FILE#/}" >$FILE ) >/dev/null 2>&1
+      echo "$CFGFILE"
       exit 0
     fi
-    umount /etc >/dev/null 2>&1
+    while umount /etc >/dev/null 2>&1; do : ; done
   fi
-done
+fi
+
+# if we get any error there, we try to restore the flash configuration.
+if mount_flash_ro; then
+  for config in $FLASHCFG/config.cur $FLASHCFG/config.bak $FLASHCFG/config.fac
+  do
+    if [ -s $config ] && [ $(tar ztf $config 2>/dev/null|wc -l) -gt 0 ]; then
+      if [ -e /etc/config.rc ]; then
+        while umount /etc >/dev/null 2>&1; do : ; done
+      fi
+      mount -n -t ramfs /etc /etc
+      (tar -C $REFERENCE --one-file-system -cf - . | tar -C /etc -xf -) >/dev/null 2>&1
+      tar -C /etc --exclude-from $EXCLUDE --strip-components=1 -zxf $config >/dev/null 2>&1
+      if [ $? -eq 0 -a -s /etc/config.rc ]; then
+        umount_flash
+        ( rm -f /etc/blkid.tab{,.old}; \
+          rm -f $FILE ; touch $FILE ; chmod 600 $FILE; \
+          flx sign --ignore-dot /etc | grep -vwF "${FILE#/}" >$FILE ) >/dev/null 2>&1
+        echo ${config##*/}
+        exit 0
+      fi
+      while umount /etc >/dev/null 2>&1; do : ; done
+    fi
+  done
+  umount_flash
+  rm -f /etc/blkid.tab{,.old} >/dev/null 2>&1
+fi
+
+# We have not found any config, so we'll build /etc from the reference etc
+# directory into a ramfs anyway so that we get a read/write /etc.
+mount -n -t ramfs /etc /etc 2>/dev/null || exit 1  # already mounted
+(tar -C $REFERENCE --one-file-system -cf - . | tar -C /etc -xf -) >/dev/null 2>&1
+( rm -f $FILE ; touch $FILE ; chmod 600 $FILE ) >/dev/null 2>&1
+( flx sign --ignore-dot /etc | grep -vwF "${FILE#/}" >$FILE ) >/dev/null 2>&1
+rm -f /etc/blkid.tab{,.old} >/dev/null 2>&1
 exit 1
diff --git a/scripts/save-etc b/scripts/save-etc
--- a/scripts/save-etc
+++ b/scripts/save-etc
@@ -1,62 +1,162 @@
 #!/bin/bash
 
-# This script unmounts /etc, mounts a ramfs onto it, and extracts
-# /flash/cfg/config.{cur,bak,fac} into it.
+# This script saves /etc onto the flash and writes a signature so that
+# it will be able to check whether files have changed next time.
+
+# get out of /flash and /etc just in case.
+cd /
 
 export PATH=/bin:/sbin:/usr/bin:/usr/sbin
-FLASH=/flash
-FLASH_CFG=$FLASH/cfg
+FLASHDIR=/flash
+FLASHCFG=$FLASHDIR/cfg
 FILE=/etc/.restored
+EXCLUDE=/usr/share/factory/ignore-files
+REFERENCE=/usr/share/factory/base-etc
 FORCE=0
 VERBOSE=0
+STDOUT=0
+QUIET=0
+
+# Mounts the flash reaw/write in $FLASHDIR.
+# This checks /proc/cmdline for the LAST 'flash=' statement, and
+# uses its value as a /dev entry to mount it read-only into $FLASHDIR.
+# Returns 0 if OK, 1 otherwise.
+# DOES NOT unmounts $FLASHDIR first if previously mounted, but returns with
+# an error indicating a resource access conflict.
+mount_flash_rw() {
+  local flash
+  flash="$(cat /proc/cmdline)"
+  if [ -n "${flash##*flash=*}" ]; then
+    [ $QUIET -eq 0 ] && echo "No flash device specified in /proc/cmdline."
+    return 1
+  fi
+  flash=${flash##*flash=}
+  flash=${flash%% *}
+  [ -n "${flash##/dev/*}" ] && flash="/dev/$flash"
+
+  [ $QUIET -eq 0 ] && echo "Mounting ${flash} on $FLASHDIR..."
+  if ! mount -w $flash $FLASHDIR >/dev/null 2>&1; then
+    rm -f /etc/blkid.tab{,.old} >/dev/null 2>&1
+    [ $QUIET -eq 0 ] && echo "Error: mount failed."
+    return 1
+  fi
+  rm -f /etc/blkid.tab{,.old} >/dev/null 2>&1
+  return 0
+}
+
+# unmounts /flash
+umount_flash() {
+  if ! umount -d $FLASHDIR >/dev/null 2>&1; then
+    cd /
+    if ! umount -d $FLASHDIR >/dev/null 2>&1; then
+      [ $QUIET -eq 0 ] && echo "Error: cannot unmount $FLASHDIR"
+      return 1
+    else
+      [ $QUIET -eq 0 ] && echo "Warning: ${0##*/} forgot to leave $FLASHDIR before unmounting it."
+    fi
+  fi
+  return 0
+}
+
+# makes an archive from files in /etc which differ from the factory config,
+# except for directories and the files we don't want to save, then exports
+# it to stdout.
+archive_etc() {
+  flx check --ignore-dot --ignore-link --ignore-date $REFERENCE=etc /etc=etc \
+    | awk '/^[+>]/ { print $9 }' \
+    | tar -C / -T - --one-file-system --numeric-owner --exclude-from $EXCLUDE -cf - \
+    | gzip -c9
+}
+
+
+# Checks what has changed since last backup. We need to use 'tar cf' because
+# we want to benefit from tar's ability to exclude files from another file.
+# The changed files are listed on stdout, relative to /.
+# WARNING! because it uses tar, it does not detect removed files.
+list_changes() {
+  if [ -r "$FILE" ]; then
+    flx check --ignore-dot --ignore-link --ignore-date file:$FILE fs:/etc \
+      | awk '/^[+>]/ { print $9 }' \
+      | tar -C / -T - --one-file-system --numeric-owner --exclude-from $EXCLUDE -cvf /dev/null 2>/dev/null
+  else
+      tar -C / --one-file-system --numeric-owner --exclude-from $EXCLUDE -cvf /dev/null etc 2>/dev/null
+  fi
+}
+
+#  
+# main
+#
 
 while [ $# -gt 0 ]; do
   if [ ".$1" = ".-f" ]; then FORCE=1
   elif [ ".$1" = ".-v" ]; then VERBOSE=1
+  elif [ ".$1" = ".-q" ]; then QUIET=1
+  elif [ ".$1" = ".-s" ]; then STDOUT=1
   else
     echo "Unknown argument: $1"
+    echo "Valid options are :"
+    echo "  -f : force write even if up-to-date ;"
+    echo "  -v : only check whether files have been modified ;"
+    echo "  -q : suppress any message. With -v, return non-0 if unsaved changes exist ;"
+    echo "  -s : dump archive to stdout instead of flash."
+    exit 1
   fi
   shift
 done
 
 if [ $VERBOSE -eq 1 ]; then
-  echo "List of files modified since last backup."
   if [ -s $FILE ]; then
-     flx check --ignore-dot fs:/etc file:$FILE | grep -vwF "${FILE#/}"
-     exit 0
+    if [ $QUIET -eq 1 ]; then
+       if [ $(list_changes | wc -l) -eq 0 ]; then
+         # nothing to save
+         exit 0
+       else
+         # unsaved changes
+         exit 1
+       fi
+    fi
+    [ $QUIET -eq 0 ] && echo "List of files modified since last backup :"
+    list_changes
+    exit 0
   else
-     echo "Backup log does not exist."
-     exit 1
+    [ $QUIET -eq 0 ] && echo "Backup log does not exist."
+    exit 1
   fi
 fi
 
-if [ $FORCE -eq 0 -a -e $FILE ] && \
-   [ $(flx check --ignore-dot fs:/etc file:$FILE | grep -cvwF "${FILE#/}") -eq 0 ]; then
-  echo "Nothing changed since last backup. Use '-f' if you want to force."
+if [ $FORCE -eq 0 -a $STDOUT -eq 0 -a -e $FILE ] && \
+  [ $(list_changes | wc -l) -eq 0 ]; then
+  [ $QUIET -eq 0 ] && echo "Nothing changed since last backup. Use '-f' if you want to force."
   exit 1;
 fi 
 
-remountw $FLASH
-rm -f $FLASH_CFG/config.new
-touch $FLASH_CFG/config.new ; chmod 600 $FLASH_CFG/config.new
-tar -C / --one-file-system --exclude=${FILE#/} -c etc | \
-  gzip -9 >$FLASH_CFG/config.new
-if [ ! -s $FLASH_CFG/config.new ]; then
-  rm -f $FLASH_CFG/config.new
-  remountr $FLASH
-  echo "Problem saving config to flash."
+if [ $STDOUT -eq 0 ]; then
+  mount_flash_rw || exit 1
+
+  rm -f $FLASHCFG/config.new
+  touch $FLASHCFG/config.new ; chmod 600 $FLASHCFG/config.new
+  archive_etc >$FLASHCFG/config.new
+else
+  archive_etc
+  exit 0
+fi
+
+if [ ! -s $FLASHCFG/config.new ]; then
+  rm -f $FLASHCFG/config.new
+  umount_flash
+  [ $QUIET -eq 0 ] && echo "Problem saving config to flash."
   exit 1
 fi
 
-mv $FLASH_CFG/config.{cur,bak} 2>/dev/null
-if ! mv $FLASH_CFG/config.{new,cur} 2>/dev/null; then
-  rm -f $FLASH_CFG/config.new
-  remountr $FLASH
-  echo "Problem saving config to flash."
+mv $FLASHCFG/config.{cur,bak} 2>/dev/null
+if ! mv $FLASHCFG/config.{new,cur} 2>/dev/null; then
+  rm -f $FLASHCFG/config.new
+  umount_flash
+  [ $QUIET -eq 0 ] && echo "Problem saving config to flash."
   exit 1
 fi
-remountr $FLASH
+umount_flash
 
 ( rm -f $FILE ; touch $FILE ; chmod 600 $FILE ) >/dev/null 2>&1
-( flx sign --ignore-dot /etc | grep -vwF "${FILE#/}" >$FILE ) 2>&1
+( flx sign --ignore-dot /etc | grep -vwF "${FILE#/}" >$FILE ) 2>/dev/null
 exit 0
